<?xml version="1.0" encoding="utf-8"?><Database Name="GestionVentas" Class="DCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-RR1BBOV\SQLEXPRESS;Initial Catalog=GestionVentas;User ID=AlejoDB" SettingsObjectName="CapaDatos.Properties.Settings" SettingsPropertyName="GestionVentasConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DetalleVenta" Member="eDetalleVenta">
    <Type Name="eDetalleVenta">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idVenta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="precio" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Producto_DetalleVenta" Member="eProducto" ThisKey="idProducto" OtherKey="id" Type="eProducto" IsForeignKey="true" />
      <Association Name="Venta_DetalleVenta" Member="eVenta" ThisKey="idVenta" OtherKey="id" Type="eVenta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Producto" Member="eProducto">
    <Type Name="eProducto">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="precio" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="marca" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Producto_DetalleVenta" Member="eDetalleVenta" ThisKey="id" OtherKey="idProducto" Type="eDetalleVenta" />
    </Type>
  </Table>
  <Table Name="dbo.Venta" Member="eVenta">
    <Type Name="eVenta">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cliente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="observaciones" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="precio" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Venta_DetalleVenta" Member="eDetalleVenta" ThisKey="id" OtherKey="idVenta" Type="eDetalleVenta" />
    </Type>
  </Table>
</Database>